server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:devdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

# Für späteres Frontend (Vite auf 5173); schadet jetzt nicht
app:
  cors:
    allowed-origins: "http://localhost:5173"
